apiVersion: v1
kind: Service
metadata:
  name: webui
  namespace: app3
  labels:
    app: webui
spec:
  selector:
    app: webui
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
